### ISSUE TITLE
Usage in example no longer works with template-haskell >=2.17

### ISSUE THREAD

**Issue by felixonmars** [GaloisInc/lumberjack#2]
Related: https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.0#deep-skolemisation

eta expand to `adjustLogAction x = local x` works, but I assume that's not the intended change for this library...

```
Building executable 'example_log' for lumberjack-1.0.0.0..
[1 of 1] Compiling Main             ( example/ExampleLog.hs, dist/build/example_log/example_log-tmp/Main.dyn_o )

example/ExampleLog.hs:69:21: error:
    • Couldn't match type: ReaderEnv -> ReaderEnv
                     with: forall (k :: * -> *). LogAction k Text -> LogAction k Text
      Expected: (forall (k :: * -> *).
                 LogAction k Text -> LogAction k Text)
                -> MyMonad a -> MyMonad a
        Actual: (ReaderEnv -> ReaderEnv) -> MyMonad a -> MyMonad a
    • In the expression: local
      In an equation for ‘adjustLogAction’: adjustLogAction = local
      In the instance declaration for ‘LoggingMonad Text MyMonad’
   |
69 |   adjustLogAction = local
   |                     ^^^^^

example/ExampleLog.hs:95:21: error:
    • Couldn't match type: ReaderEnv2 -> ReaderEnv2
                     with: forall (k :: * -> *).
                           LogAction k LogMessage -> LogAction k LogMessage
      Expected: (forall (k :: * -> *).
                 LogAction k LogMessage -> LogAction k LogMessage)
                -> MyMonad2 a -> MyMonad2 a
        Actual: (ReaderEnv2 -> ReaderEnv2) -> MyMonad2 a -> MyMonad2 a
    • In the expression: local
      In an equation for ‘adjustLogAction’: adjustLogAction = local
      In the instance declaration for ‘LoggingMonad LogMessage MyMonad2’
   |
95 |   adjustLogAction = local
   |                     ^^^^^
```

**Comment by kquick** [comment]
Thanks for catching this!  Fixed in 1.0.0.1.
